USER_COLOR=$(tput setaf 2)
HOST_COLOR=$(tput setaf 3)
DIR_COLOR=$(tput setaf 6)
PROMPT_COLOR=$(tput setaf 5)
RESET=$(tput sgr0)

PS1="\n\[$USER_COLOR\]\u \[$PROMPT_COLOR\]at \[$HOST_COLOR\]\h \[$PROMPT_COLOR\]in \[$DIR_COLOR\]\w\n\[$PROMPT_COLOR\]\$\[$RESET\] "

alias grep="grep --color=auto"
alias vi="nvim"

if [ $(uname) == 'Darwin' ]; then
	alias ls="ls -G"
else
	alias ls="ls --color=auto"
fi
